### ISSUE TITLE
I can't access the site when I type mcsynergy.nl/production-graphs

### ISSUE THREAD

**Issue by Josian2004** [MC-Synergy/MCSAnalyser-FrontEnd#10]
Please automatically redirect http to https so that mcsynergy.nl/production-graphs also works :)

![image](https://user-images.githubusercontent.com/72351214/201074163-ad17e36e-e6c3-4f14-810b-0de176997bfd.png)

**Comment by crazyvinvin** [comment]
Hi @Josian2004, could you maybe try if it's working from your side now?

Let me know.

**Comment by Josian2004** [comment]
@crazyvinvin, I can confirm that it works now
