### ISSUE TITLE
Enlarge margin at the top of the nav-bar

### ISSUE THREAD

**Issue by lazyjesjes** [MC-Synergy/MCSAnalyser-FrontEnd#2]
Enlarge the top margin at the nav-bar with 300%. 
Might look better that way.

**Comment by crazyvinvin** [comment]
Margin was currently 0, I have added 8 pixels to the top. This will be updated in the next release.

Please close the ticket if you think it looks good.

**Comment by lazyjesjes** [comment]
Still looks a bit too shabby, try making it 16px. If you don't want to, don't do it and close the ticket.
