### ISSUE TITLE
Add refresh button in corner of graph

### ISSUE THREAD

**Issue by CtrlAnimate** [MC-Synergy/MCSAnalyser-FrontEnd#3]
It's annoying to press F5 when you're only using your mouse. User experience is greatly enhanced when you have to switch the least number of times.

**Comment by crazyvinvin** [comment]
A refresh button is already present in almost every browser, so I don't see the need to add a refresh button for the whole page. However I might be able to add a refresh feature for specific graphs. 
This would translate to: 
As a user I want a graph's data to be reloaded after I click a reload button in the top right corner of a graph.
